= WXX

The goal of this package is to provide methods to read and write Worldographer WXX files.

== Worldographer Applications
Inkwell publishes two versions of Worldographer.

The older version has an opening splash with "Worldographer / Hexographer 2."
It was first released in 2017 so we use "H2017" as the code for the XML schema used by this version.

The newer version has an opening splash with just "Worldographer."
Inkwell calls it "Worldographer 2025," so we use "W2025" as the code for the XML schema used by this version.

These codes (H2017 and W2025) help us keep the XML schema versions straight.

We generally call either version "Worldographer."

== Data Format Versioning

The version number in the data is for the application that created the file.
There is no versioning of the data format for H2017 files.

1. map.release is only in W2025 files and identifies the Worldographer application major version.
2. map.version is in both files and identifies the application minor version.
3. map.schema is only in W2025 files and identifies the XML Schema version.


The following table maps values from the XML data to the WXX Package Schema Version.

|===
|Encoding|map.release|map.version|map.schema|WXX Package Schema Version

|UTF-16/BE||1.73||1.0.0
|UTF-16/BE||1.74||1.0.0
|UTF-16/BE|2025|1.10|1.01|2.0.0
|===

[NOTE]
====
Only the combinations of values listed in the table are supported by this package.
====

== Design Notes

A WXX file contains compressed XML data using a UTF-16 (big-endian) encoding.

When we import the WXX file, we unzip the data, convert to UTF-8, and then unmarshall to our `XML` data type.
This process depends on the data format version.

[WARNING]
====
The design of this package is not fixed; the following comments on the directory structure are out of date.
====

The XML data type is not meant to be used outside of this package, so it is defined in an `internal` folder.
This makes the type very clumsy to use, but makes the intention very clear.

Please read
https://dave.cheney.net/2019/10/06/use-internal-packages-to-reduce-your-public-api-surface[Dave Cheney's article]
for details on the `internal` designation.

== Adapters

I am assuming that we'll use _adapters_ to decode and encode the Worldographer data file.

In general, we'll always decode the Worldographer data file to an internal Map structure.
We'll use an external adapter to convert to the global `Map` structure.

Likewise, we'll use an adapter to convert the global `Map` structure to our internal Map when we need to write data,
and then we'll encode that Map to write the Worldographer data file.

[NOTE]
====
See the `cmd/wxxdemo` for an example of how to use the pipelines.
====

=== Decoding Pipeline

Decoding starts by reading the `.wxx` file into a `[]byte`.
The `gzutf16` package provides a ReadCloser for this.


Our `UTF-16 to UTF-8` adapter verifies that the data starts with a `<?xml version='1.0' encoding='utf-16'?>` header.
If it doesn't, an error is returned.
Otherwise, the header is removed and the remainder of the slice is converted to UTF-8 encoding.

The generic decoder looks for the Worldographer Version near the start of the data.
If it can't find it, an error is returned.
Otherwise, the Worldographer Version is used to determine the XML Data Format.
That determines which version of the decoder is used to unmarshal the data into our `Map` structure.

[NOTE]
====
It is important to note that we only have one version of this `Map`.
====

The `Map` is an exported Go struct and is documented in a separate file.

I imagine that the typical command will read a `.wxx` into a `Map`, manipulate it, then write it back to a `.wxx` file.

=== Encoding Pipeline

The encoding pipeline converts a `Map` structure to a `[]byte` containing the compressed XML data for Worldographer.

You must specify the Worldographer Version to target for the encoding.
That version determines the version of the XML Data Format to create.
The version is also stored in the XML data.

The generic encoder uses the Worldographer Version to pick a suitable encoder.
If it can't find one, an error is returned.
Otherwise, the `Map` data is translated into XML data.

The XML data is marshalled to a `[]byte` using a UTF-8 encoding.
That slice is returned.

Our `UTF-8 to UTF-16` adapter converts the slice to UTF-16 and adds the `<?xml version='1.0' encoding='utf-16'?>` header.
It returns a new `[]byte`.

Our `gzip` adapter compresses the slice and returns a new `[]byte`.

Encoding ends by writing the slice to a file with the `.wxx` extension.
The `gzutf16` package provides a Buffer to help with that and an WriteFile function, too.
